import { Hono } from "hono";
import { verifyAccessToken } from "@/lib/auth";

type Variables = {
  userId: string;
};

const aiRouter = new Hono<{ Variables: Variables }>();

// Protect: ADMIN only
aiRouter.use("*", async (c, next) => {
  try {
    const authHeader = c.req.header("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return c.json({ error: "Unauthorized" }, 401);
    }
    const token = authHeader.split(" ")[1];
    const payload = verifyAccessToken(token);

    if (payload.role !== "ADMIN") {
      return c.json({ error: "Forbidden: Admins only" }, 403);
    }
    
    c.set("userId", payload.userId);
    await next();
  } catch {
    return c.json({ error: "Invalid token" }, 401);
  }
});

// Mock Data structure for AI usage over the month
const mockUsageHistory = [
  { date: "Oct 21", calls: 45, cost: 0.12 },
  { date: "Oct 22", calls: 120, cost: 0.45 },
  { date: "Oct 23", calls: 86, cost: 0.31 },
  { date: "Oct 24", calls: 15, cost: 0.04 },
  { date: "Oct 25", calls: 200, cost: 0.85 },
];

aiRouter.get("/usage", async (c) => {
  // In a real scenario, this queries a TokenUsage table
  const totalCalls = mockUsageHistory.reduce((acc, obj) => acc + obj.calls, 0);
  const totalCost = mockUsageHistory.reduce((acc, obj) => acc + obj.cost, 0);

  return c.json({
    metrics: {
      totalCalls,
      totalCost,
      estimatedMonthlyBill: totalCost * 4.5, // Mock projection
    },
    history: mockUsageHistory,
  });
});

aiRouter.post("/generate-proposal", async (c) => {
  const { businessName, industry, goals } = await c.req.json();

  // MOCK: In production we'd `fetch("https://api.openai.com/...`)
  // Here we just simulate an AI response generation based on the parameters
  
  const generatedProposal = `
# Executive Proposal: ${businessName}

## 1. Overview
At DigiGrow, we specialize in accelerating growth for businesses in the **${industry}** industry. This proposal outlines a comprehensive strategy to address your unique challenges and help you reach your primary objective: *"${goals}"*.

## 2. Our Approach
- **Phase 1: Deep Discovery.** Complete technical audit of existing digital assets.
- **Phase 2: Strategy Definition.** Establishing clear KPI benchmarks and go-to-market messaging.
- **Phase 3: Execution Engine.** Phased rollout of SEO and targeted PPC campaigns to align with your objectives.
- **Phase 4: Optimization.** Bi-weekly performance reviews and strategic pivoting.

## 3. Recommended Services
Based on your needs, we recommend compiling a customized retainer focused on:
* **Search Engine Optimization (SEO)** to compound organic leads.
* **Performance Marketing (Meta/Google Ads)** for immediate bottom-of-the-funnel acquisitions.
* **Conversion Rate Optimization (CRO)** to ensure the traffic we generate actually converts into revenue.

## 4. Investment
Our proposed customized growth plan starts at **$2,500/mo**.

*Generated by AI Assistant on ${new Date().toLocaleDateString()}*
`;

  return c.json({ proposal: generatedProposal });
});

export default aiRouter;
